### PR TITLE
Improve renderer view

### PR DESCRIPTION
**Pull request by jacobcoughenour**
I converted the renderer view properties list into a table for better readability and made the view size inherit from the content.

### CODE REVIEW

**Comment by jsantell** [comment]
Awesome, could you rebase this on top of the recent changes?

**Comment by jsantell** [comment]
Hmm looks like some of the commits got messed up and included some commits from master..

**Comment by jacobcoughenour** [comment]
I think I fixed it now...

**Comment by jsantell** [comment]
thanks for the change, looks good!

**Pull request merged**
